# Then we add init tasks when the environment is started.
# We will add more DBs to this as we move forward.
tasks:
  - name: Python Dependencies
    before: pip install -r requirements.txt
  - name: MySQL Client
    before: sudo apt install -y mysql-client
  - name: Start PhpMyAdmin
    command: docker run -d -e PMA_HOST=$DBHOST -e PMA_USER=$DBUSER -e PMA_PASSWORD=$DBPASS -p 8001:80 phpmyadmin
  - name: Start uvicorn
    command: sleep 30 && /usr/bin/bash /workspace/fastapi-demo/preview.sh

# We have also customized the environment so that whenever we run an app on port 8000 it
# is automatically made public and is opened up in a browser.
ports:
  - name: API
    description: Preview changes to your application
    port: 8000-8010
    onOpen: open-browser
    visibility: public